# Use O2C_Template Customized Notebook Template

In [1]:
import random
from faker import Faker
import pandas as pd

In [2]:
from fosforml.model_manager.snowflakesession import get_session
my_session = get_session()

In [3]:
fake = Faker('en_US')

# Customer Data Setup

In [43]:
# Generate Customers
def generate_customers(num_customers=150):
    customers = []
    for _ in range(num_customers):
        customer = {
            'CustomerID': 'CID-' + fake.uuid4(),
            'CompanyType':fake.company_suffix(),
            'ContactDetails': fake.phone_number(),
            'EmailDetails': fake.company_email(),
            'AddressDetails':fake.address(),
            'AdminDetails':fake.administrative_unit(),
            'CreditLimit': random.randint(30000, 100000),
            'CustomerSince': f"YR-{random.randint(2015, 2022)}", 
            #'CreditRating': random.choice(['very poor', 'fair', 'good', 'very good','exceptional'])
        }
        customers.append(customer)
    return customers

In [44]:
# Generate Data
customers = generate_customers()

In [45]:
customers_name = ['CleverOffice','Stackers','PreScott Works','MomentA','BOXED'
,'JinkOffice','HomeEssentials','BallPoint','WhaleBack','Formica'
,'Starton Inc','Anabrige LLP','Hammers and Nails','BoreHole LLC'
,'Indra Secure Co-rp','CortiTech ITC','DOLCH ','Sutura'
,'StarStruck LLC','BARCTL LLC','Limae Inc','Rivet','Marathon'
,'Valiant','Filum','TautaLog','Pin&Fix','JamPack','MasterStik'
,'CLIC','Nestables','CAPSTASH','Tappit','MashMart','TruSource'
,'ODD Sends','Pen Scoop','ASCRIBE LLP','Wire works','EXPRESSR'
,'FULCRO','SOLID BOX','LYSIS Logo','CARDIOID','Herculean Inc'
,'OTTAVA','BLUE Ribbon','Master Bind ','Thinkies','Five Point'
,'Connect iBuy','Lion Mark','Deskify','BestTry','PLOTSHOP'
,'Office Fuel','Oasis Cuff','CoraPress','SuperShapes','BeeBows'
,'Locale Mart','TetherLink','Comestor','Knox Paper','NECESSITE'
,'Corner Spike','SPACE MAX','Easy Dealy','Star Tech','KLIXX'
,'Phyllon LLP','Planisphere','A1 Creased','ONYX','HomeBright'
,'NextBolt','Pinch Hops','Popplin','Mercer and Sons','Jackson-Hughes'
,'Moran Ltd','Baldwin PLC','Tucker Ltd','Allen Inc','Rodriguez Group'
,'Taylor Ltd','Mahoney PLC','Robinson Group','Mcmillan LLC'
,'Bailey-Roberts','Rivera PLC','Potter Group','Mckay-Davis','Valencia Group'
,'Haynes-Jackson','Klein Inc','Davis-Rose','Watson-Miller','Smith LLC'
,'Jackson and Sons'
,'BrightWorks', 'EcoSphere', 'TechWave', 'PrimeSource', 'Apex Innovations',
'GreenLeaf', 'UrbanEdge', 'Quantum Solutions', 'Vertex Ventures', 'NexGen',
'FusionCorp', 'BlueSky Enterprises', 'PioneerTech', 'Elite Systems', 'Skyline Industries',
'ProActive', 'Innovatech', 'CoreDynamics', 'SynergyWorks', 'NextEra',
'Optima', 'Zenith', 'Vanguard', 'Summit Solutions', 'Infinity Group',
'AlphaTech', 'GlobalReach', 'MetroLink', 'Visionary', 'DynamicEdge',
'PrimeTech', 'FutureWave', 'EcoTech', 'UrbanCore', 'SkyHigh',
'ProLink', 'Innovative Solutions', 'CoreTech', 'SynergyCorp', 'NextGen Solutions',
'OptiMax', 'Zenith Enterprises', 'Vanguard Innovations', 'SummitTech', 'Infinity Solutions',
'Alpha Innovations', 'GlobalTech', 'MetroTech', 'Visionary Solutions', 'Dynamic Innovations']

In [46]:
df_customers = pd.DataFrame(customers)

In [47]:
# Function to determine Payment_Terms based on CreditLimit
def determine_payment_terms(rating):
    if rating < 50000:
        return 'Net 15 days'
    elif 50000 <= rating < 75000:
        return 'Net 30 days'
    elif 75000 <= rating < 90000:
        return 'Net 45 days'
    else:
        return 'Net 60 days'

In [48]:
# Assign RatingType based on Rating value
df_customers['PaymentTerms'] = df_customers['CreditLimit'].apply(determine_payment_terms)

In [49]:
# Function to determine CreditLimitType based on CreditLimit/Rating value
def determine_rating_type(rating):
    if rating < 40000:
        return 'Very Low'
    elif 40000 <= rating < 55000:
        return 'Low'
    elif 55000 <= rating < 70000:
        return 'Medium'
    elif 70000 <= rating < 85000:
        return 'High'
    else:
        return 'Very High'

In [50]:
# Assign RatingType based on Rating value
df_customers['CreditLimitType'] = df_customers['CreditLimit'].apply(determine_rating_type)

In [51]:
df_customers['CustomerName'] = customers_name

In [52]:
CustomerType = ['Construction Materials','Office Supplies','Construction Materials','Food Beverages'
,'Office Supplies','Construction Materials','Healthcare','Food Beverages','Automotive'
,'Food Beverages','Food Beverages','Construction Materials','Construction Materials'
,'Construction Materials','Automotive','Food Beverages','Food Beverages','Food Beverages'
,'Consumer Goods','Consumer Goods','Healthcare','Office Supplies','Office Supplies'
,'Office Supplies','Healthcare','Office Supplies','Construction Materials','Office Supplies'
,'Office Supplies','Office Supplies','Food Beverages','Consumer Goods','Consumer Goods'
,'Food Beverages','Office Supplies','Office Supplies','Food Beverages','Office Supplies'
,'Construction Materials','Food Beverages','Automotive','Office Supplies','Office Supplies'
,'Consumer Goods','Automotive','Food Beverages','Office Supplies','Office Supplies'
,'Food Beverages','Food Beverages','Food Beverages','Food Beverages','Consumer Goods'
,'Healthcare','Food Beverages','Healthcare','Food Beverages','Food Beverages','Healthcare'
,'Automotive','Food Beverages','Food Beverages','Food Beverages','Consumer Goods'
,'Healthcare','Food Beverages','Automotive','Consumer Goods','Food Beverages'
,'Food Beverages','Consumer Goods','Consumer Goods','Automotive','Consumer Goods'
,'Consumer Goods','Construction Materials','Consumer Goods','Consumer Goods','Consumer Goods'
,'Consumer Goods','Industrial Equipment','Industrial Equipment','Industrial Equipment'
,'Industrial Equipment','Consumer Goods','Industrial Equipment','Healthcare','Healthcare'
,'Healthcare','Automotive','Industrial Equipment','Construction Materials','Automotive'
,'Construction Materials','Consumer Goods','Consumer Goods','Consumer Goods','Consumer Goods'
,'Industrial Equipment','Consumer Goods'
,'Office Supplies','Office Supplies','Office Supplies','Office Supplies','Office Supplies'
,'Consumer Goods','Consumer Goods','Consumer Goods','Consumer Goods','Consumer Goods'
,'Food Beverages','Food Beverages','Food Beverages','Food Beverages','Food Beverages'
,'Construction Materials','Construction Materials','Construction Materials','Construction Materials','Construction Materials'
,'Healthcare','Healthcare','Healthcare','Healthcare','Healthcare'
,'Automotive','Automotive','Automotive','Automotive','Automotive'
,'Industrial Equipment','Industrial Equipment','Industrial Equipment','Industrial Equipment','Industrial Equipment'
,'Office Supplies','Office Supplies','Office Supplies','Office Supplies','Office Supplies'
,'Consumer Goods','Consumer Goods','Consumer Goods','Consumer Goods','Consumer Goods'
,'Food Beverages','Food Beverages','Food Beverages','Food Beverages','Food Beverages']

In [53]:
df_customers['CustomerType'] = CustomerType

In [54]:
df_customers.columns

Index(['CustomerID', 'CompanyType', 'ContactDetails', 'EmailDetails',
       'AddressDetails', 'AdminDetails', 'CreditLimit', 'CustomerSince',
       'PaymentTerms', 'CreditLimitType', 'CustomerName', 'CustomerType'],
      dtype='object')

In [55]:
df_customers.head()

,CustomerID,CompanyType,ContactDetails,EmailDetails,AddressDetails,AdminDetails,CreditLimit,CustomerSince,PaymentTerms,CreditLimitType,CustomerName,CustomerType
0,CID-8f625c7b-d43b-4436-80ad-4cbba77c779e,PLC,+1-875-276-6325x2418,jacob45@bailey-murphy.net,"033 Daniel Route\nMartinshire, IN 02876",Utah,53429,YR-2019,Net 30 days,Low,CleverOffice,Construction Materials
1,CID-7defd2b6-7ee3-4371-bd5e-a34d6179ead7,Ltd,(537)281-7306x652,romerojustin@moore-bentley.com,"6527 Ross Canyon\nCherylstad, OH 67499",Vermont,87832,YR-2022,Net 45 days,Very High,Stackers,Office Supplies
2,CID-2decf55f-b43b-42ab-a3a1-1d1b6c3d40a4,Ltd,001-824-063-1538x302,griffithsuzanne@anderson.com,49148 Mclaughlin Groves Suite 661\nJoannemouth...,South Dakota,94936,YR-2016,Net 60 days,Very High,PreScott Works,Construction Materials
3,CID-a6c36d38-d2f8-4728-9e7f-6a6ca14d1928,LLC,+1-949-057-6105x819,mgonzalez@morales-massey.com,USNS Kline\nFPO AP 68761,Rhode Island,30025,YR-2016,Net 15 days,Very Low,MomentA,Food Beverages
4,CID-7b7ae865-2ef0-4330-8bb9-a2cfc2645003,Group,+1-159-031-2775,william48@martinez.com,"494 Jamie Mountains Apt. 435\nSouth Tonifort, ...",New Hampshire,57617,YR-2022,Net 30 days,Medium,BOXED,Office Supplies

In [56]:
df_train_sf=my_session.createDataFrame(
        df_customers.values.tolist(),
        schema=df_customers.columns.tolist())
df_train_sf.write.mode("overwrite").save_as_table("FDC_HORIZONTAL.O2C_BRONZE.KNA1")

# Product Data setup

In [66]:
df_product = pd.read_csv('product_files.csv')

In [68]:
df_product.shape

(72, 6)

In [69]:
df_product.head()

,ProductCategory,ProductType,Quantity,UnitPrice,SupplierName,SupplierID
0,Office Supplies,Laser Printer,100,425,Sure Source,SUP--8f625c7b-d43b-4436-80ad-4cbba77c779e
1,Office Supplies,Ergonomic Chair,1000,299,Sure Source,SUP--8f625c7b-d43b-4436-80ad-4cbba77c779e
2,Office Supplies,Standing Desk,1000,420,Sure Source,SUP--8f625c7b-d43b-4436-80ad-4cbba77c779e
3,Office Supplies,Wireless Keyboard,1000,78,Sure Source,SUP--8f625c7b-d43b-4436-80ad-4cbba77c779e
4,Office Supplies,Office Stationery Set,1000,15,Sure Source,SUP--8f625c7b-d43b-4436-80ad-4cbba77c779e

In [70]:
def generate_products(data):
    data['ProductID'] = ''
    # Iterate over rows and columns
    for index, row in data.iterrows():
        data.at[index, 'ProductID'] = 'PID-' + fake.uuid4()
    return data

In [71]:
df_product = generate_products(df_product)

In [72]:
df_product.columns

Index(['ProductCategory', 'ProductType', 'Quantity', 'UnitPrice',
       'SupplierName', 'SupplierID', 'ProductID'],
      dtype='object')

In [73]:
df_train_sf=my_session.createDataFrame(
        df_product.values.tolist(),
        schema=df_product.columns.tolist())
df_train_sf.write.mode("overwrite").save_as_table("FDC_HORIZONTAL.O2C_BRONZE.MARA")

# Status Scenarios for data Manipulation

In [20]:
order_status = ['Approved','Rejected','Cancelled']
shipment_status = ['Pending','Picked','Shipped','In-Transit','Delivered','Returned']
invoice_status = ['PendingApproval','Approved','Sent','Paid','Cancelled']

In [21]:
import itertools

In [22]:
# Generate all possible combinations of statuses
combinations = list(itertools.product(order_status,shipment_status,invoice_status))

In [23]:
# Create a DataFrame to store the combinations
columns = ["order_status", "shipment_status", "invoice_status"]
df = pd.DataFrame(combinations, columns=columns)

In [24]:
df[df['order_status']=='Approved']

   order_status shipment_status   invoice_status
0      Approved         Pending  PendingApproval
1      Approved         Pending         Approved
2      Approved         Pending             Sent
3      Approved         Pending             Paid
4      Approved         Pending        Cancelled
5      Approved          Picked  PendingApproval
6      Approved          Picked         Approved
7      Approved          Picked             Sent
8      Approved          Picked             Paid
9      Approved          Picked        Cancelled
10     Approved         Shipped  PendingApproval
11     Approved         Shipped         Approved
12     Approved         Shipped             Sent
13     Approved         Shipped             Paid
14     Approved         Shipped        Cancelled
15     Approved      In-Transit  PendingApproval
16     Approved      In-Transit         Approved
17     Approved      In-Transit             Sent
18     Approved      In-Transit             Paid
19     Approved      In-Transit        Cancelled
20     Approved       Delivered  PendingApproval
21     Approved       Delivered         Approved
22     Approved       Delivered             Sent
23     Approved       Delivered             Paid
24     Approved       Delivered        Cancelled
25     Approved        Returned  PendingApproval
26     Approved        Returned         Approved
27     Approved        Returned             Sent
28     Approved        Returned             Paid
29     Approved        Returned        Cancelled

# Setup Order, OrderItems, Shipment and Invoice Data for Fulfilled Orders

In [4]:
import random
from fosforml.model_manager.snowflakesession import get_session
my_session = get_session()

In [5]:
table_name = 'KNA1'

sf_df = my_session.sql("select * from {}".format(table_name))
df_customers = sf_df.to_pandas()

In [6]:
table_name = 'MARA'

sf_df = my_session.sql("select * from {}".format(table_name))
df_product = sf_df.to_pandas()

In [7]:
# Assuming you already have the customers and products dataframes
customers = df_customers['CUSTOMERID'].tolist()
products = df_product[['PRODUCTID', 'UNITPRICE']].to_dict('records')

# Code to Generate Orderdate using Monthly Distribution

In [8]:
# Function to generate a random date between two dates
def random_date(start_date, end_date):
    delta = end_date - start_date
    random_days = random.randint(0, delta.days)
    return start_date + timedelta(days=random_days)

In [117]:
import random
from datetime import datetime, timedelta

def generate_order_dates(year, no_of_orders, month_distribution, exclude_months):
    # Filter out the excluded months from the distribution
    filtered_distribution = {month: prob for month, prob in month_distribution.items() if month not in exclude_months}
    
    # Normalize the filtered distribution
    total_prob = sum(filtered_distribution.values())
    normalized_distribution = {month: prob / total_prob for month, prob in filtered_distribution.items()}
    
    # Generate cumulative distribution for the filtered months
    cumulative_distribution = []
    cumulative_sum = 0
    for month in range(1, 13):
        if month in normalized_distribution:
            cumulative_sum += normalized_distribution[month]
            cumulative_distribution.append((month, cumulative_sum))
    
    # Function to get a random month based on the distribution
    def get_random_month():
        rand = random.random()
        for month, cum_prob in cumulative_distribution:
            if rand <= cum_prob:
                return month
    
    # Generate random dates
    random_dates = []
    for _ in range(no_of_orders):
        random_month = get_random_month()
        # Get a random day in the selected month
        while True:
            random_day = random.randint(1, 31)
            try:
                random_date = datetime(year=year, month=random_month, day=random_day)
                random_dates.append(random_date.strftime("%m-%d-%Y"))
                break
            except ValueError:
                continue
    
    return random_dates

In [118]:
# Example usage
year = 2022
no_of_orders = 22950
month_distribution = {
    1: 0.11, 2: 0.06, 3: 0.09, 4: 0.06, 5: 0.12, 6: 0.06, 7: 0.08, 8: 0.07, 9: 0.13, 10: 0.06, 11: 0.09, 12: 0.07
}
exclude_months = []  # Example months to exclude

orderdate_2022 = generate_order_dates(year, no_of_orders, month_distribution, exclude_months)

In [123]:
min(orderdate_2022), max(orderdate_2022)

('01-01-2022', '12-31-2022')

In [119]:
# Example usage
year = 2023
no_of_orders = 32300
month_distribution = {
    1: 0.11, 2: 0.06, 3: 0.09, 4: 0.06, 5: 0.12, 6: 0.06, 7: 0.08, 8: 0.07, 9: 0.13, 10: 0.06, 11: 0.09, 12: 0.07
}
exclude_months = []  # Example months to exclude

orderdate_2023 = generate_order_dates(year, no_of_orders, month_distribution, exclude_months)

In [122]:
min(orderdate_2023), max(orderdate_2023)

('01-01-2023', '12-31-2023')

In [120]:
# Example usage
year = 2024
no_of_orders = 29750
month_distribution = {
    1: 0.11, 2: 0.06, 3: 0.09, 4: 0.06, 5: 0.12, 6: 0.06, 7: 0.08, 8: 0.07, 9: 0.13, 10: 0.06, 11: 0.09, 12: 0.07
}
exclude_months = [10, 11, 12]  # Example months to exclude

orderdate_2024 = generate_order_dates(year, no_of_orders, month_distribution, exclude_months)

In [121]:
min(orderdate_2024), max(orderdate_2024)

('01-01-2024', '09-30-2024')

In [127]:
orderdate = orderdate_2022 + orderdate_2023 + orderdate_2024
orderdate.sort()

In [128]:
from collections import Counter
from datetime import datetime

# Convert the order dates to datetime objects
order_dates = [datetime.strptime(date, "%m-%d-%Y") for date in orderdate]

# Calculate yearly order counts
yearly_counts = Counter(date.year for date in order_dates)

# Calculate monthly order counts
monthly_counts = Counter((date.year, date.month) for date in order_dates)

In [129]:
# Print yearly order counts
print("Yearly Order Counts:")
for year, count in yearly_counts.items():
    print(f"{year}: {count}")

Yearly Order Counts:
2022: 22950
2023: 32300
2024: 29750

In [131]:
# Print monthly order counts
print("\nMonthly Order Counts:")
for (year, month), count in monthly_counts.items():
    print(f"{year}-{month:02d}: {count}")

Monthly Order Counts:
2022-01: 2440
2023-01: 3524
2024-01: 4218
2022-02: 1439
2023-02: 1942
2024-02: 2261
2022-03: 2012
2023-03: 2796
2024-03: 3460
2022-04: 1373
2023-04: 1983
2024-04: 2238
2022-05: 2783
2023-05: 4009
2024-05: 4567
2022-06: 1381
2023-06: 1929
2024-06: 2257
2022-07: 1820
2023-07: 2589
2024-07: 3048
2022-08: 1646
2023-08: 2242
2024-08: 2734
2022-09: 2953
2023-09: 4134
2024-09: 4967
2022-10: 1381
2023-10: 1926
2022-11: 2113
2023-11: 2922
2022-12: 1609
2023-12: 2304

In [133]:
def add_days(input_date, range1, range2):

    if isinstance(input_date, str):    
    # Convert orderdate string back to datetime object
        input_date = datetime.strptime(input_date, '%m-%d-%Y')

    # Generate a random number of days 
    additional_days = random.randint(range1, range2)

    # Calculate the new date
    new_date = input_date + timedelta(days=additional_days)

    # Convert the new date back to string if needed
    new_date = new_date.strftime('%m-%d-%Y')

    return new_date

In [134]:
# Function to determine Payment_Terms based on CreditLimit
def determine_payment_range(rating):
    if rating < 50000:
        return 15
    elif 50000 <= rating < 75000:
        return 25
    elif 75000 <= rating < 90000:
        return 30
    else:
        return 45

In [135]:
Supplier_Delivery = {'Sure Source' : [5,10]
,'Prime Partners' : [3,7]
,'Wholesale Wizards' : [1,3]
,'Supply Solutions' : [5,15]
,'Procure Plus' : [10,15]
}

In [86]:
# List to store orders
orders_fulfill = []
items_fulfill = []
shipment_fulfill = []
invoice_fulfill = []

# Generate orders
for i in range(85000):
    # Filter products matching the customer's type
    customer = df_customers.sample(n=1)
    matching_products = df_product[df_product['PRODUCTCATEGORY'] == customer.iloc[0]['CUSTOMERTYPE']]
    num_items = random.choice([1,2,3])  # Each order has a random number of items between 1 and 3
    
    supplier_name = matching_products.iloc[0]['SUPPLIERNAME']
    supplier_delivery_startrange, supplier_delivery_endrange = Supplier_Delivery[supplier_name]
    
    customerid = customer.iloc[0]['CUSTOMERID']
    orderid = 'OR-' + fake.uuid4()
    #orderdate = orders[i]
    orderdate = orderdate[i]
    #orderdate = random_date(start_date, end_date).strftime('%m-%d-%Y')
    orderstatus = 'Approved'
    orderamount = 0
    ordercount = 0
    invoice_range = 0
    
    shipmentid = 'SP-' + fake.uuid4()
    shipmentdate = add_days(orderdate, supplier_delivery_startrange, supplier_delivery_endrange)

    delivery_range = 5
    if supplier_name in ['Prime Partners','Wholesale Wizards']:
        delivery_range = 2
        
    deliverydate = add_days(shipmentdate, 2 ,3)
    deliveredOn = add_days(deliverydate,1,delivery_range) 

    invoiceid = 'IN-' + fake.uuid4()
    invoicedate = add_days(deliveredOn,0,1)

    credit_limit = customer.iloc[0]['CREDITLIMIT']
    #print (customerid, credit_limit)
    invoice_range = determine_payment_range(credit_limit)
    invoiceduedate = add_days(invoicedate,invoice_range-1, invoice_range)
        
    for _ in range(num_items):
        products = matching_products.sample(n=1)
        product_type = products.iloc[0]['PRODUCTTYPE']
        quantity = random.randint(1, products.iloc[0]['QUANTITY'])  # Generate a random quantity for each order item
        unit_price = products.iloc[0]['UNITPRICE']
        total_price = quantity * unit_price
        orderamount += total_price
        ordercount += 1
        matching_products = matching_products[matching_products['PRODUCTTYPE'] != product_type]
        orderitemid = 'OI-' + fake.uuid4()


        items_dict = {
            'ORDERID' : orderid,
            'ORDERITEMID': orderitemid,
            'PRODUCTID': products.iloc[0]['PRODUCTID'],
            'PRODUCTNAME' : products.iloc[0]['PRODUCTTYPE'],
            'ORDERQUANTITY' :quantity,
            'UNITPRICE' : unit_price,
            'ORDERVALUE' : total_price
        }

        items_fulfill.append(items_dict)
    
    payment_status = 'ONTIME_PAYMENT'
    if orderamount > 0.95 * credit_limit:  # If order amount exceeds 95% of the credit limit
        paymentdate = add_days(invoicedate,invoice_range+10, invoice_range+15)  # Delay payment by 10 days
        payment_status = 'LATE_PAYMENT'
    elif orderamount > 0.90 * credit_limit:  # If order amount exceeds 90% of the credit limit
        paymentdate = add_days(invoicedate,invoice_range+5, invoice_range+10)  # Delay payment by 15 days
        payment_status = 'LATE_PAYMENT'
    else:
        paymentdate = add_days(invoicedate,1, invoice_range) #No delay in payments
    
        

    orders_dict = {
        'ORDERID' : orderid,
        'CUSTOMERID': customerid,
        'CUSTOMERNAME': customer.iloc[0]['CUSTOMERNAME'],
        'PRODUCTID': matching_products.iloc[0]['PRODUCTID'],
        'PRODUCTCATEGORY': matching_products.iloc[0]['PRODUCTCATEGORY'],
        'ORDERDATE': orderdate,
        'ORDERSTATUS': orderstatus,
        'ORDERAMOUNT' :orderamount,
        'ORDERCOUNT' : ordercount
    }

    orders_fulfill.append(orders_dict)

    shipment_dict = {
        'SHIPMENTID': shipmentid,
        'ORDERID' : orderid,
        'SHIPMENTDATE': shipmentdate,
        'DELIVERYDATE': deliverydate,
        'DELIVEREDON' :deliveredOn,
        'CARRIER' : random.choice(['FedEx', 'UPS', 'DHL', 'USPS']),
        'SHIPMENTSTATUS' : 'Delivered'
    }

    shipment_fulfill.append(shipment_dict)

    invoice_dict = {
        'INVOICEID': invoiceid,
        'ORDERID' : orderid,
        'INVOICEDATE': invoicedate,
        'INVOICEDUEDATE': invoiceduedate,
        'PAYMENTDATE' : paymentdate,
        'INVOICESTATUS': payment_status,
        'PAYMENTMETHOD': random.choice(['Wire Transfers','Cards','Checks','Mobile Payments'])
    }

    invoice_fulfill.append(invoice_dict)

In [87]:
# Create a DataFrame for orders
df_orders_fulfill = pd.DataFrame(orders_fulfill)
df_items_fulfill = pd.DataFrame(items_fulfill)
df_shipment_fulfill = pd.DataFrame(shipment_fulfill)
df_invoice_fulfill = pd.DataFrame(invoice_fulfill)

In [88]:
print (df_orders_fulfill.shape)
print (df_items_fulfill.shape)
print (df_shipment_fulfill.shape)
print (df_invoice_fulfill.shape)

(85000, 9)
(170445, 7)
(85000, 7)
(85000, 7)

In [89]:
df_orders_fulfill.head()

,ORDERID,CUSTOMERID,CUSTOMERNAME,PRODUCTID,PRODUCTCATEGORY,ORDERDATE,ORDERSTATUS,ORDERAMOUNT,ORDERCOUNT
0,OR-e38e4d3c-ba74-4b33-a0fa-259bc142c300,CID-9181bd58-bd85-436b-b7ac-67f4a59e968d,BrightWorks,PID-4af92409-4d2d-4ac0-adac-0ced1926de84,Office Supplies,01-15-2022,Approved,40656,1
1,OR-ce739e96-bb20-4c83-9044-1ba635585ec7,CID-e87ac050-480a-4859-acff-9a612e836579,Comestor,PID-8c9fa52a-4d73-4173-bb71-8cbe17cae1c1,Food Beverages,11-08-2022,Approved,1368,2
2,OR-bf373277-4ae1-4047-a6a2-6767313d1b67,CID-b17e79cc-51e7-4d2b-b959-c1a11978e2e4,Summit Solutions,PID-3ab40a2e-51f5-4b53-bc88-5014641aa701,Healthcare,09-24-2022,Approved,84030,3
3,OR-ace44a8a-ad5f-4ab1-88c2-9b22f321db1a,CID-52e8bbfa-f985-4592-b81a-e4839b65c2fc,Mckay-Davis,PID-6cf6400d-1e83-4e24-ac90-f53754533308,Automotive,03-10-2022,Approved,197795,3
4,OR-ea31a153-11d5-494c-ab36-26e85f10a0cf,CID-7e947c84-6280-43b0-b95d-708464d44146,CLIC,PID-4af92409-4d2d-4ac0-adac-0ced1926de84,Office Supplies,05-09-2022,Approved,5985,1

In [90]:
df_shipment_fulfill.head(5)

,SHIPMENTID,ORDERID,SHIPMENTDATE,DELIVERYDATE,DELIVEREDON,CARRIER,SHIPMENTSTATUS
0,SP-b17a2a9b-ca81-458a-b1b4-71350dfef5a8,OR-e38e4d3c-ba74-4b33-a0fa-259bc142c300,01-21-2022,01-23-2022,01-27-2022,FedEx,Delivered
1,SP-2423a422-ee76-48c6-ad68-81d0fa320edc,OR-ce739e96-bb20-4c83-9044-1ba635585ec7,11-11-2022,11-13-2022,11-15-2022,DHL,Delivered
2,SP-3edeb1fc-c527-4ae8-898a-5dfcd46d6f04,OR-bf373277-4ae1-4047-a6a2-6767313d1b67,09-27-2022,09-29-2022,10-01-2022,UPS,Delivered
3,SP-faa48ae9-1520-4032-a3cb-6959e0d40df4,OR-ace44a8a-ad5f-4ab1-88c2-9b22f321db1a,03-21-2022,03-23-2022,03-25-2022,DHL,Delivered
4,SP-bc6a7bbb-f72b-482a-8492-32a725a21760,OR-ea31a153-11d5-494c-ab36-26e85f10a0cf,05-18-2022,05-21-2022,05-26-2022,FedEx,Delivered

In [91]:
df_invoice_fulfill.head(5)

,INVOICEID,ORDERID,INVOICEDATE,INVOICEDUEDATE,PAYMENTDATE,INVOICESTATUS,PAYMENTMETHOD
0,IN-9d42a60c-101f-49f2-a2ae-701b0c3bfc6c,OR-e38e4d3c-ba74-4b33-a0fa-259bc142c300,01-27-2022,02-26-2022,02-22-2022,ONTIME_PAYMENT,Mobile Payments
1,IN-2fd1c22e-c711-4ad3-8f52-1f4c02a876f1,OR-ce739e96-bb20-4c83-9044-1ba635585ec7,11-16-2022,11-30-2022,11-30-2022,ONTIME_PAYMENT,Checks
2,IN-b5208d14-8e57-4d64-84c2-c896d1948af0,OR-bf373277-4ae1-4047-a6a2-6767313d1b67,10-02-2022,10-27-2022,11-08-2022,LATE_PAYMENT,Wire Transfers
3,IN-74977f72-64d5-4628-a3a7-2f8147dcfd5e,OR-ace44a8a-ad5f-4ab1-88c2-9b22f321db1a,03-25-2022,04-18-2022,04-30-2022,LATE_PAYMENT,Wire Transfers
4,IN-ad5ff1ea-e496-4f99-a009-faf4624b61e4,OR-ea31a153-11d5-494c-ab36-26e85f10a0cf,05-26-2022,06-19-2022,06-01-2022,ONTIME_PAYMENT,Cards

In [92]:
df_invoice_fulfill['INVOICESTATUS'].value_counts()

INVOICESTATUS
ONTIME_PAYMENT    46986
LATE_PAYMENT      38014
Name: count, dtype: int64

# Setup Order, OrderItems, Shipment and Invoice Data for recent Pending Orders

In [93]:
# List to store orders
orders_fulfill_1 = []
items_fulfill_1 = []
shipment_fulfill_1 = []
invoice_fulfill_1 = []

start_date = datetime.strptime('09-01-2024', '%m-%d-%Y')
end_date = datetime.strptime('10-01-2024', '%m-%d-%Y')

# Generate orders
for i in range(1500):
    # Filter products matching the customer's type
    customer = df_customers.sample(n=1)
    matching_products = df_product[df_product['PRODUCTCATEGORY'] == customer.iloc[0]['CUSTOMERTYPE']]
    num_items = random.choice([1,2,3])  # Each order has a random number of items between 1 and 3

    supplier_name = matching_products.iloc[0]['SUPPLIERNAME']
    supplier_delivery_startrange, supplier_delivery_endrange = Supplier_Delivery[supplier_name]

    customerid = customer.iloc[0]['CUSTOMERID']
    orderid = 'OR-' + fake.uuid4()
    orderdate = random_date(start_date, end_date).strftime('%m-%d-%Y')
    orderstatus = 'Approved'
    orderamount = 0
    ordercount = 0
    invoice_range = 0
    
    shipmentid = 'SP-' + fake.uuid4()
    shipmentdate = add_days(orderdate, supplier_delivery_startrange, supplier_delivery_endrange)
    #shipmentdate = add_days(orderdate, 2,7)

    delivery_range = 5
    if supplier_name in ['Prime Partners','Wholesale Wizards']:
        delivery_range = 2
        
    deliverydate = add_days(shipmentdate, 2 ,3)
    deliveredOn = add_days(deliverydate,1,delivery_range) 
    #deliverydate = add_days(shipmentdate, 1,4)
    #deliveredOn = add_days(deliverydate,0,3) 

    invoiceid = 'IN-' + fake.uuid4()
    invoicedate = add_days(deliveredOn,0,1)

    credit_limit = customer.iloc[0]['CREDITLIMIT']
    #print (customerid, credit_limit)
    invoice_range = determine_payment_range(credit_limit)
    invoiceduedate = add_days(invoicedate,invoice_range-1, invoice_range)

    #invoiceduedate = add_days(invoicedate,5,7)
    #paymentdate = add_days(invoicedate,1,15)

    shipment_status =  random.choice(['Picked','Shipped','In-Transit','Delivered'])
    
    for _ in range(num_items):
        products = matching_products.sample(n=1)
        product_type = products.iloc[0]['PRODUCTTYPE']
        quantity = random.randint(1, products.iloc[0]['QUANTITY'])  # Generate a random quantity for each order item
        unit_price = products.iloc[0]['UNITPRICE']
        total_price = quantity * unit_price
        orderamount += total_price
        ordercount += 1
        matching_products = matching_products[matching_products['PRODUCTTYPE'] != product_type]
        orderitemid = 'OI-' + fake.uuid4()
        
        items_dict = {
            'ORDERID' : orderid,
            'ORDERITEMID': orderitemid,
            'PRODUCTID': products.iloc[0]['PRODUCTID'],
            'PRODUCTNAME' : products.iloc[0]['PRODUCTTYPE'],
            'ORDERQUANTITY' :quantity,
            'UNITPRICE' : unit_price,
            'ORDERVALUE' : total_price
        }

        items_fulfill_1.append(items_dict)
    invoice_status = ''
    if shipment_status == 'Delivered':
        invoice_status = 'Sent'
    else:
        invoice_status = random.choice(['PendingApproval','Approved'])
        invoicedate = '12-31-9999'
        invoiceduedate = '12-31-9999'
        paymentdate = '12-31-9999'
        deliveredOn = '12-31-9999'

    orders_dict = {
        'ORDERID' : orderid,
        'CUSTOMERID': customerid,
        'CUSTOMERNAME': customer.iloc[0]['CUSTOMERNAME'],
        'PRODUCTID': matching_products.iloc[0]['PRODUCTID'],
        'PRODUCTCATEGORY': matching_products.iloc[0]['PRODUCTCATEGORY'],
        'ORDERDATE': orderdate,
        'ORDERSTATUS': orderstatus,
        'ORDERAMOUNT' :orderamount,
        'ORDERCOUNT' : ordercount
    }

    orders_fulfill_1.append(orders_dict)

    shipment_dict = {
        'SHIPMENTID': shipmentid,
        'ORDERID' : orderid,
        'SHIPMENTDATE': shipmentdate,
        'DELIVERYDATE': deliverydate,
        'DELIVEREDON' :deliveredOn,
        'CARRIER' : random.choice(['FedEx', 'UPS', 'DHL', 'USPS']),
        'SHIPMENTSTATUS' : shipment_status
    }

    shipment_fulfill_1.append(shipment_dict)

    invoice_dict = {
        'INVOICEID': invoiceid,
        'ORDERID' : orderid,
        'INVOICEDATE': invoicedate,
        'INVOICEDUEDATE': invoiceduedate,
        'PAYMENTDATE' : paymentdate,
        'INVOICESTATUS': invoice_status,
        'PAYMENTMETHOD': 'Not-Applicable'
    }

    invoice_fulfill_1.append(invoice_dict)

In [94]:
# Create a DataFrame for orders
df_orders_fulfill_1 = pd.DataFrame(orders_fulfill_1)
df_items_fulfill_1 = pd.DataFrame(items_fulfill_1)
df_shipment_fulfill_1 = pd.DataFrame(shipment_fulfill_1)
df_invoice_fulfill_1 = pd.DataFrame(invoice_fulfill_1)

In [97]:
print (df_orders_fulfill_1.shape)
print (df_items_fulfill_1.shape)
print (df_shipment_fulfill_1.shape)
print (df_invoice_fulfill_1.shape)

(1500, 9)
(2992, 7)
(1500, 7)
(1500, 7)

In [98]:
df_orders_fulfill_1.head(2)

,ORDERID,CUSTOMERID,CUSTOMERNAME,PRODUCTID,PRODUCTCATEGORY,ORDERDATE,ORDERSTATUS,ORDERAMOUNT,ORDERCOUNT
0,OR-5be6ec17-fde3-4919-ba94-0c2fa32a966f,CID-e1f16e78-6a59-4440-9fff-98ab53bf1a5f,Five Point,PID-df71fb0e-604f-4ded-8a16-850f47932a2a,Food Beverages,09-02-2024,Approved,5295,3
1,OR-4a039e7c-629b-4c2a-88e3-83ec1f64062b,CID-222088d8-1bb3-45a4-82c4-2b66a4d9ddc3,Pen Scoop,PID-8c9fa52a-4d73-4173-bb71-8cbe17cae1c1,Food Beverages,09-30-2024,Approved,13785,2

In [99]:
df_items_fulfill_1.head(2)

,ORDERID,ORDERITEMID,PRODUCTID,PRODUCTNAME,ORDERQUANTITY,UNITPRICE,ORDERVALUE
0,OR-5be6ec17-fde3-4919-ba94-0c2fa32a966f,OI-bf96b65f-a023-42f7-9eb9-d8e5ea70a6f4,PID-efe86bed-b844-4638-a39c-d0c5225d5243,Cold-Pressed Juice,266,11,2926
1,OR-5be6ec17-fde3-4919-ba94-0c2fa32a966f,OI-e682adc4-d471-41c9-a24d-64c1b0b47bee,PID-2484256d-02c1-488a-a17d-39eab93719b6,Dried Fruits,128,5,640

In [100]:
df_shipment_fulfill_1.head()

,SHIPMENTID,ORDERID,SHIPMENTDATE,DELIVERYDATE,DELIVEREDON,CARRIER,SHIPMENTSTATUS
0,SP-d0632c28-446f-4cf9-881c-cd560b535947,OR-5be6ec17-fde3-4919-ba94-0c2fa32a966f,09-03-2024,09-05-2024,12-31-9999,DHL,Picked
1,SP-82edfd6b-9483-41da-8bbd-1eae70f6b04f,OR-4a039e7c-629b-4c2a-88e3-83ec1f64062b,10-03-2024,10-05-2024,12-31-9999,DHL,In-Transit
2,SP-eb2110b4-549f-4dc6-a6ca-ecdd7cabd1c5,OR-14609912-e83c-455a-b4dd-3119aa1a3419,09-27-2024,09-30-2024,12-31-9999,UPS,Shipped
3,SP-70015cc6-3bf7-4acc-89bb-941fcd4ec433,OR-c0aee43d-4e38-44b9-8c1d-9153f3685b42,09-25-2024,09-27-2024,09-29-2024,DHL,Delivered
4,SP-82a46f3c-61e2-4d7d-8e92-e81be1c1544d,OR-89c99cf1-a02a-4d8a-8368-d4191219de01,09-29-2024,10-01-2024,12-31-9999,UPS,Picked

In [101]:
df_invoice_fulfill_1.head(3)

,INVOICEID,ORDERID,INVOICEDATE,INVOICEDUEDATE,PAYMENTDATE,INVOICESTATUS,PAYMENTMETHOD
0,IN-c9efa24b-0575-4b92-b60a-2c78c4a37a55,OR-5be6ec17-fde3-4919-ba94-0c2fa32a966f,12-31-9999,12-31-9999,12-31-9999,PendingApproval,Not-Applicable
1,IN-86d096a7-ace8-4d36-8e61-42d8b74e7813,OR-4a039e7c-629b-4c2a-88e3-83ec1f64062b,12-31-9999,12-31-9999,12-31-9999,PendingApproval,Not-Applicable
2,IN-902066dd-7ebb-49bb-ad64-19d4013bcbf6,OR-14609912-e83c-455a-b4dd-3119aa1a3419,12-31-9999,12-31-9999,12-31-9999,Approved,Not-Applicable

In [102]:
df_orders = pd.concat([df_orders_fulfill,df_orders_fulfill_1],axis=0)
df_items = pd.concat([df_items_fulfill, df_items_fulfill_1],axis=0)
df_shipments = pd.concat([df_shipment_fulfill, df_shipment_fulfill_1],axis=0)
df_invoice = pd.concat([df_invoice_fulfill, df_invoice_fulfill_1],axis=0)

In [103]:
df_orders.shape

(86500, 9)

In [104]:
df_items.shape

(173437, 7)

In [105]:
df_shipments.shape

(86500, 7)

In [106]:
df_invoice.shape

(86500, 7)

# Push Data to Snowflake

In [107]:
df_train_sf=my_session.createDataFrame(
        df_orders.values.tolist(),
        schema=df_orders.columns.tolist())
df_train_sf.write.mode("overwrite").save_as_table("FDC_HORIZONTAL.O2C_BRONZE.VBAK")

In [108]:
df_train_sf=my_session.createDataFrame(
        df_items.values.tolist(),
        schema=df_items.columns.tolist())
df_train_sf.write.mode("overwrite").save_as_table("FDC_HORIZONTAL.O2C_BRONZE.VBAP")

In [109]:
df_train_sf=my_session.createDataFrame(
        df_shipments.values.tolist(),
        schema=df_shipments.columns.tolist())
df_train_sf.write.mode("overwrite").save_as_table("FDC_HORIZONTAL.O2C_BRONZE.LIKP")

In [110]:
df_train_sf=my_session.createDataFrame(
        df_invoice.values.tolist(),
        schema=df_invoice.columns.tolist())
df_train_sf.write.mode("overwrite").save_as_table("FDC_HORIZONTAL.O2C_BRONZE.VBRK")